services:
  ionic-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "18100:8100"
    stdin_open: true
    tty: true

volumes:
  node_modules:
